"""中文电影片名映射表
优先覆盖训练集中出现的电影，未映射的显示英文原名
"""

# 热门电影中文片名映射（英文  中文）
CN_TITLES = {
    "Toy Story": "玩具总动员",
    "Jumanji": "勇敢者游戏",
    "Grumpier Old Men": "老当益壮",
    "Heat": "盗火线",
    "Sabrina": "情归巴黎",
    "GoldenEye": "黄金眼",
    "The American President": "美国总统",
    "Casino": "赌城风云",
    "Sense and Sensibility": "理智与情感",
    "Ace Ventura: When Nature Calls": "神探飞机头2",
    "Get Shorty": "矮子当道",
    "Leaving Las Vegas": "离开拉斯维加斯",
    "Twelve Monkeys (a.k.a. 12 Monkeys)": "十二猴子",
    "Babe": "小猪宝贝",
    "Dead Man Walking": "死囚漫步",
    "Clueless": "独领风骚",
    "Seven (a.k.a. Se7en)": "七宗罪",
    "Pocahontas": "风中奇缘",
    "The Usual Suspects": "非常嫌疑犯",
    "Mr. Holland's Opus": "生命因你而动听",
    "From Dusk Till Dawn": "杀出个黎明",
    "Broken Arrow": "断箭",
    "Happy Gilmore": "高尔夫球也疯狂",
    "Braveheart": "勇敢的心",
    "Taxi Driver": "出租车司机",
    "The Birdcage": "鸟笼",
    "Bad Boys": "绝地战警",
    "Apollo 13": "阿波罗13号",
    "Batman Forever": "永远的蝙蝠侠",
    "Casper": "鬼马小精灵",
    "Congo": "刚果惊魂",
    "Crimson Tide": "赤色风暴",
    "Desperado": "杀人三部曲",
    "Die Hard: With a Vengeance": "虎胆龙威3",
    "First Knight": "第一骑士",
    "Johnny Mnemonic": "非常任务",
    "Judge Dredd": "特警判官",
    "The Net": "网络惊魂",
    "Waterworld": "未来水世界",
    "Clerks": "疯狂店员",
    "Disclosure": "叛逆性骚扰",
    "Dumb & Dumber (Dumb and Dumber)": "阿呆与阿瓜",
    "Ed Wood": "艾德·伍德",
    "Interview with the Vampire": "夜访吸血鬼",
    "Star Wars: Episode IV - A New Hope": "星球大战4：新希望",
    "Legends of the Fall": "燃情岁月",
    "Natural Born Killers": "天生杀人狂",
    "Outbreak": "恐怖地带",
    "Léon: The Professional": "这个杀手不太冷",
    "Pulp Fiction": "低俗小说",
    "Quiz Show": "机智问答",
    "Stargate": "星际之门",
    "The Santa Clause": "圣诞老人",
    "The Shawshank Redemption": "肖申克的救赎",
    "Star Trek: Generations": "星际迷航7",
    "Tommy Boy": "老板也疯狂",
    "What's Eating Gilbert Grape": "不一样的天空",
    "While You Were Sleeping": "二见钟情",
    "Ace Ventura: Pet Detective": "神探飞机头",
    "Clear and Present Danger": "燃眉追击",
    "The Client": "终极证人",
    "The Crow": "乌鸦",
    "Forrest Gump": "阿甘正传",
    "Four Weddings and a Funeral": "四个婚礼和一个葬礼",
    "The Lion King": "狮子王",
    "The Mask": "变相怪杰",
    "Maverick": "赌侠马华力",
    "Naked Gun 33 1/3": "白头神探3",
    "Speed": "生死时速",
    "True Lies": "真实的谎言",
    "Addams Family Values": "亚当斯一家2",
    "Beverly Hills Cop III": "比弗利山警探3",
    "City Slickers II": "城市滑头2",
    "Cliffhanger": "绝岭雄风",
    "Coneheads": "大头玩偶",
    "Dave": "冒牌总统",
    "Demolition Man": "越空狂龙",
    "The Firm": "糖衣陷阱",
    "The Fugitive": "亡命天涯",
    "Hot Shots! Part Deux": "反斗神鹰2",
    "In the Line of Fire": "火线狙击",
    "Jurassic Park": "侏罗纪公园",
    "Last Action Hero": "幻影英雄",
    "Mrs. Doubtfire": "窈窕奶爸",
    "Philadelphia": "费城故事",
    "The Piano": "钢琴别恋",
    "Robin Hood: Men in Tights": "罗宾汉也疯狂",
    "Schindler's List": "辛德勒的名单",
    "Sleepless in Seattle": "西雅图夜未眠",
    "Blade Runner": "银翼杀手",
    "The Nightmare Before Christmas": "圣诞夜惊魂",
    "The Three Musketeers": "三剑客",
    "Tombstone": "墓碑镇",
    "True Romance": "真实罗曼史",
    "Home Alone": "小鬼当家",
    "Ghost": "人鬼情未了",
    "Aladdin": "阿拉丁",
    "Terminator 2: Judgment Day": "终结者2",
    "Dances with Wolves": "与狼共舞",
    "Batman": "蝙蝠侠",
    "The Silence of the Lambs": "沉默的羔羊",
    "Snow White and the Seven Dwarfs": "白雪公主和七个小矮人",
    "Beauty and the Beast": "美女与野兽",
    "Pinocchio": "木偶奇遇记",
    "Pretty Woman": "风月俏佳人",
    "Fargo": "冰血暴",
    "Mission: Impossible": "碟中谍",
    "Dragonheart": "龙之心",
    "Space Jam": "空中大灌篮",
    "The Truth About Cats & Dogs": "众里寻她兜错路",
    "The Rock": "勇闯夺命岛",
    "Twister": "龙卷风",
    "Dr. Strangelove": "奇爱博士",
    "Trainspotting": "猜火车",
    "Independence Day (a.k.a. ID4)": "独立日",
    "The Cable Guy": "有线电视修理工",
    "Eraser": "蒸发密令",
    "The Nutty Professor": "肥佬教授",
    "The Godfather": "教父",
    "Vertigo": "迷魂记",
    "Rear Window": "后窗",
    "North by Northwest": "西北偏北",
    "Some Like It Hot": "热情似火",
    "Casablanca": "卡萨布兰卡",
    "The Wizard of Oz": "绿野仙踪",
    "Citizen Kane": "公民凯恩",
    "2001: A Space Odyssey": "2001太空漫游",
    "It's a Wonderful Life": "生活多美好",
    "Mary Poppins": "欢乐满人间",
    "The Sound of Music": "音乐之声",
    "Die Hard": "虎胆龙威",
    "Willy Wonka & the Chocolate Factory": "欢乐糖果屋",
    "A Fish Called Wanda": "一条叫旺达的鱼",
    "Monty Python's Life of Brian": "万世魔星",
    "Reservoir Dogs": "落水狗",
    "Platoon": "野战排",
    "E.T. the Extra-Terrestrial": "E.T.外星人",
    "Top Gun": "壮志凌云",
    "The Abyss": "深渊",
    "Monty Python and the Holy Grail": "巨蟒与圣杯",
    "Wallace & Gromit: The Wrong Trousers": "超级无敌掌门狗",
    "One Flew Over the Cuckoo's Nest": "飞越疯人院",
    "Star Wars: Episode V - The Empire Strikes Back": "星球大战5：帝国反击战",
    "The Princess Bride": "公主新娘",
    "Raiders of the Lost Ark": "夺宝奇兵",
    "Brazil": "妙想天开",
    "Aliens": "异形2",
    "The Good, the Bad and the Ugly": "黄金三镖客",
    "12 Angry Men": "十二怒汉",
    "A Clockwork Orange": "发条橙",
    "To Kill a Mockingbird": "杀死一只知更鸟",
    "Apocalypse Now": "现代启示录",
    "Star Wars: Episode VI - Return of the Jedi": "星球大战6：绝地归来",
    "Goodfellas": "好家伙",
    "Alien": "异形",
    "Army of Darkness": "鬼玩人3",
    "Psycho": "惊魂记",
    "The Blues Brothers": "蓝调兄弟",
    "The Godfather: Part II": "教父2",
    "Full Metal Jacket": "全金属外壳",
    "Amadeus": "莫扎特传",
    "Annie Hall": "安妮·霍尔",
    "The Sting": "骗中骗",
    "The Terminator": "终结者",
    "Dead Poets Society": "死亡诗社",
    "The Graduate": "毕业生",
    "Chinatown": "唐人街",
    "The Shining": "闪灵",
    "Stand by Me": "伴我同行",
    "Groundhog Day": "土拨鼠之日",
    "Back to the Future": "回到未来",
    "Cool Hand Luke": "铁窗喋血",
    "Young Frankenstein": "新科学怪人",
    "Fantasia": "幻想曲",
    "This Is Spinal Tap": "摇滚万万岁",
    "Indiana Jones and the Last Crusade": "夺宝奇兵3",
    "Field of Dreams": "梦幻之地",
    "Butch Cassidy and the Sundance Kid": "虎豹小霸王",
    "When Harry Met Sally...": "当哈利遇到莎莉",
    "Star Trek: First Contact": "星际迷航8：第一类接触",
    "Die Hard 2": "虎胆龙威2",
    "Star Trek II: The Wrath of Khan": "星际迷航2：可汗之怒",
    "Batman Returns": "蝙蝠侠归来",
    "Grease": "油脂",
    "Jaws": "大白鲨",
    "Mars Attacks!": "火星人玩转地球",
    "Jerry Maguire": "甜心先生",
    "Raising Arizona": "抚养亚利桑那",
    "Scream": "惊声尖叫",
    "Donnie Brasco": "忠奸人",
    "Liar Liar": "大话王",
    "Grosse Pointe Blank": "杀手无假期",
    "Austin Powers: International Man of Mystery": "王牌大贱谍",
    "The Fifth Element": "第五元素",
    "The Lost World: Jurassic Park": "侏罗纪公园2",
    "Con Air": "空中监狱",
    "Face/Off": "变脸",
    "Men in Black (a.k.a. MIB)": "黑衣人",
    "Contact": "超时空接触",
    "Air Force One": "空军一号",
    "The Hunt for Red October": "猎杀红色十月",
    "L.A. Confidential": "洛城机密",
    "The Game": "心理游戏",
    "Chasing Amy": "猜·情·寻",
    "The Full Monty": "一脱到底",
    "The Devil's Advocate": "魔鬼代言人",
    "Gattaca": "千钧一发",
    "Starship Troopers": "星河战队",
    "The Truman Show": "楚门的世界",
    "Good Will Hunting": "心灵捕手",
    "Titanic": "泰坦尼克号",
    "The Big Lebowski": "谋杀绿脚趾",
    "The Wedding Singer": "婚礼歌手",
    "As Good as It Gets": "尽善尽美",
    "Armageddon": "绝世天劫",
    "There's Something About Mary": "我为玛丽狂",
    "Rocky": "洛奇",
    "Rain Man": "雨人",
    "The Breakfast Club": "早餐俱乐部",
    "The Exorcist": "驱魔人",
    "Lethal Weapon": "致命武器",
    "The Goonies": "七宝奇谋",
    "The Mask of Zorro": "佐罗的面具",
    "Back to the Future Part II": "回到未来2",
    "Back to the Future Part III": "回到未来3",
    "Saving Private Ryan": "拯救大兵瑞恩",
    "Honey, I Shrunk the Kids": "亲爱的，我把孩子缩小了",
    "The Jungle Book": "森林王子",
    "Lady and the Tramp": "小姐与流浪汉",
    "The Little Mermaid": "小美人鱼",
    "Splash": "现代美人鱼",
    "Tron": "电子世界争霸战",
    "Indiana Jones and the Temple of Doom": "夺宝奇兵2",
    "Blade": "刀锋战士",
    "Beetlejuice": "阴间大法师",
    "The Untouchables": "铁面无私",
    "A Few Good Men": "义海雄风",
    "Edward Scissorhands": "剪刀手爱德华",
    "My Cousin Vinny": "我的表兄维尼",
    "Pleasantville": "欢乐谷",
    "Life Is Beautiful": "美丽人生",
    "American History X": "美国X档案",
    "Enemy of the State": "全民公敌",
    "A Bug's Life": "虫虫危机",
    "Rushmore": "青春年少",
    "Shakespeare in Love": "莎翁情史",
    "Romancing the Stone": "绿宝石",
    "You've Got Mail": "电子情书",
    "Crocodile Dundee": "鳄鱼邓迪",
    "Office Space": "上班一条虫",
    "Planet of the Apes": "人猿星球",
    "Lock, Stock & Two Smoking Barrels": "两杆大烟枪",
    "The Matrix": "黑客帝国",
    "10 Things I Hate About You": "我恨你的十件事",
    "Election": "校园风云",
    "The Mummy": "木乃伊",
    "Star Wars: Episode I - The Phantom Menace": "星球大战1：幽灵的威胁",
    "Superman": "超人",
    "The Rocky Horror Picture Show": "洛基恐怖秀",
    "Notting Hill": "诺丁山",
    "Austin Powers: The Spy Who Shagged Me": "王牌大贱谍2",
    "Run Lola Run (Lola rennt)": "罗拉快跑",
    "Arachnophobia": "小魔星",
    "South Park: Bigger, Longer and Uncut": "南方公园",
    "Wild Wild West": "飙风战警",
    "American Pie": "美国派",
    "The Blair Witch Project": "女巫布莱尔",
    "Eyes Wide Shut": "大开眼戒",
    "Ghostbusters (a.k.a. Ghost Busters)": "捉鬼敢死队",
    "The Sixth Sense": "第六感",
    "Airplane!": "空前绝后满天飞",
    "Big": "飞越未来",
    "A Christmas Story": "圣诞故事",
    "American Beauty": "美国丽人",
    "Total Recall": "全面回忆",
    "Ferris Bueller's Day Off": "春天不是读书天",
    "Goldfinger": "007之金手指",
    "Fight Club": "搏击俱乐部",
    "RoboCop": "机械战警",
    "Who Framed Roger Rabbit": "谁陷害了兔子罗杰",
    "Being John Malkovich": "成为约翰·马尔科维奇",
    "Spaceballs": "太空炮弹",
    "Dogma": "怒犯天条",
    "Sleepy Hollow": "断头谷",
    "Toy Story 2": "玩具总动员2",
    "The Green Mile": "绿里奇迹",
    "Magnolia": "木兰花",
    "Galaxy Quest": "银河追缉令",
    "Wayne's World": "反斗智多星",
    "Erin Brockovich": "永不妥协",
    "Animal House": "动物屋",
    "Close Encounters of the Third Kind": "第三类接触",
    "High Fidelity": "失恋排行榜",
    "Hook": "铁钩船长",
    "Predator": "铁血战士",
    "American Psycho": "美国精神病人",
    "Caddyshack": "疯狂高尔夫",
    "Gladiator": "角斗士",
    "Mission: Impossible II": "碟中谍2",
    "Blazing Saddles": "神枪小子",
    "Gone in 60 Seconds": "极速60秒",
    "Chicken Run": "小鸡快跑",
    "The Patriot": "爱国者",
    "Scary Movie": "惊声尖笑",
    "X-Men": "X战警",
    "Almost Famous": "几近成名",
    "Best in Show": "物极必反",
    "Meet the Parents": "拜见岳父大人",
    "Requiem for a Dream": "梦之安魂曲",
    "Charlie's Angels": "霹雳娇娃",
    "Unbreakable": "不死劫",
    "Crouching Tiger, Hidden Dragon": "卧虎藏龙",
    "Snatch": "偷拐抢骗",
    "What Women Want": "男人百分百",
    "Cast Away": "荒岛余生",
    "Miss Congeniality": "特工佳丽",
    "O Brother, Where Art Thou?": "逃狱三王",
    "Traffic": "毒品网络",
    "Memento": "记忆碎片",
    "Blow": "大毒枭",
    "Bridget Jones's Diary": "BJ单身日记",
    "Scarface": "疤面煞星",
    "Shrek": "怪物史莱克",
    "Moulin Rouge": "红磨坊",
    "A.I. Artificial Intelligence": "人工智能",
    "Legally Blonde": "律政俏佳人",
    "The Others": "小岛惊魂",
    "Training Day": "训练日",
    "Zoolander": "超级名模",
    "Mulholland Drive": "穆赫兰道",
    "Donnie Darko": "死亡幻觉",
    "Monsters, Inc.": "怪兽电力公司",
    "Harry Potter and the Sorcerer's Stone": "哈利波特与魔法石",
    "Ocean's Eleven": "十一罗汉",
    "Amelie": "天使爱美丽",
    "The Royal Tenenbaums": "天才一族",
    "The Lord of the Rings: The Fellowship of the Ring": "指环王1：护戒使者",
    "A Beautiful Mind": "美丽心灵",
    "Black Hawk Down": "黑鹰坠落",
    "Ice Age": "冰河世纪",
    "My Big Fat Greek Wedding": "我的盛大希腊婚礼",
    "Spider-Man": "蜘蛛侠",
    "Star Wars: Episode II - Attack of the Clones": "星球大战2：克隆人的进攻",
    "The Bourne Identity": "谍影重重",
    "Minority Report": "少数派报告",
    "Men in Black II (a.k.a. MIIB) (a.k.a. MIB 2)": "黑衣人2",
    "Austin Powers in Goldmember": "王牌大贱谍3",
    "Signs": "天兆",
    "Spirited Away": "千与千寻",
    "Bowling for Columbine": "科伦拜恩的保龄",
    "Harry Potter and the Chamber of Secrets": "哈利波特与密室",
    "The Lord of the Rings: The Two Towers": "指环王2：双塔奇兵",
    "Gangs of New York": "纽约黑帮",
    "Catch Me If You Can": "猫鼠游戏",
    "City of God (Cidade de Deus)": "上帝之城",
    "X2: X-Men United": "X战警2",
    "The Matrix Reloaded": "黑客帝国2：重装上阵",
    "Bruce Almighty": "冒牌天神",
    "Finding Nemo": "海底总动员",
    "The Italian Job": "偷天换日",
    "28 Days Later": "惊变28天",
    "Pirates of the Caribbean: The Curse of the Black Pearl": "加勒比海盗",
    "Lost in Translation": "迷失东京",
    "School of Rock": "摇滚校园",
    "Mystic River": "神秘河",
    "Kill Bill: Vol. 1": "杀死比尔1",
    "The Matrix Revolutions": "黑客帝国3：矩阵革命",
    "Love Actually": "真爱至上",
    "The Last Samurai": "最后的武士",
    "Big Fish": "大鱼",
    "The Lord of the Rings: The Return of the King": "指环王3：王者无敌",
    "Eternal Sunshine of the Spotless Mind": "暖暖内含光",
    "Kill Bill: Vol. 2": "杀死比尔2",
    "Shrek 2": "怪物史莱克2",
    "The Day After Tomorrow": "后天",
    "Harry Potter and the Prisoner of Azkaban": "哈利波特与阿兹卡班的囚徒",
    "Super Size Me": "超大号的我",
    "Spider-Man 2": "蜘蛛侠2",
    "Anchorman: The Legend of Ron Burgundy": "王牌播音员",
    "I, Robot": "我，机器人",
    "The Bourne Supremacy": "谍影重重2",
    "Shaun of the Dead": "僵尸肖恩",
    "The Incredibles": "超人总动员",
    "Million Dollar Baby": "百万美元宝贝",
    "Charlie and the Chocolate Factory": "查理和巧克力工厂",
    "Sin City": "罪恶之城",
    "Crash": "撞车",
    "Star Wars: Episode III - Revenge of the Sith": "星球大战3：西斯的复仇",
    "Mr. & Mrs. Smith": "史密斯夫妇",
    "Batman Begins": "蝙蝠侠：侠影之谜",
    "War of the Worlds": "世界大战",
    "Wedding Crashers": "婚礼傲客",
    "Serenity": "冲出宁静号",
    "The 40-Year-Old Virgin": "四十岁的老处男",
    "Harry Potter and the Goblet of Fire": "哈利波特与火焰杯",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe": "纳尼亚传奇",
    "V for Vendetta": "V字仇杀队",
    "X-Men: The Last Stand": "X战警3：背水一战",
    "Pirates of the Caribbean: Dead Man's Chest": "加勒比海盗2",
    "Little Miss Sunshine": "阳光小美女",
    "Borat": "波拉特",
    "Pan's Labyrinth": "潘神的迷宫",
    "The Departed": "无间道风云",
    "Children of Men": "人类之子",
    "The Prestige": "致命魔术",
    "Casino Royale": "007：大战皇家赌场",
    "Blood Diamond": "血钻",
    "Ratatouille": "美食总动员",
    "Hot Fuzz": "热血警探",
    "300": "斯巴达300勇士",
    "Knocked Up": "一夜大肚",
    "Pirates of the Caribbean: At World's End": "加勒比海盗3",
    "Harry Potter and the Order of the Phoenix": "哈利波特与凤凰社",
    "The Bourne Ultimatum": "谍影重重3",
    "Superbad": "太坏了",
    "No Country for Old Men": "老无所依",
    "I Am Legend": "我是传奇",
    "Juno": "朱诺",
    "The Dark Knight": "蝙蝠侠：黑暗骑士",
    "Iron Man": "钢铁侠",
    "Kung Fu Panda": "功夫熊猫",
    "WALL·E": "机器人总动员",
    "Slumdog Millionaire": "贫民窟的百万富翁",
    "Inglourious Basterds": "无耻混蛋",
    "Star Trek": "星际迷航",
    "Up": "飞屋环游记",
    "The Hangover": "宿醉",
    "Harry Potter and the Half-Blood Prince": "哈利波特与混血王子",
    "District 9": "第九区",
    "Zombieland": "僵尸之地",
    "Avatar": "阿凡达",
    "Sherlock Holmes": "大侦探福尔摩斯",
    "Shutter Island": "禁闭岛",
    "How to Train Your Dragon": "驯龙高手",
    "Toy Story 3": "玩具总动员3",
    "Inception": "盗梦空间",
    "The Social Network": "社交网络",
    "The King's Speech": "国王的演讲",
    "Harry Potter and the Deathly Hallows: Part 2": "哈利波特与死亡圣器(下)",
    "The Avengers": "复仇者联盟",
    "The Hunger Games": "饥饿游戏",
    "The Dark Knight Rises": "蝙蝠侠：黑暗骑士崛起",
    "Skyfall": "007：大破天幕杀机",
    "Django Unchained": "被解救的姜戈",
    "The Wolf of Wall Street": "华尔街之狼",
    "The Grand Budapest Hotel": "布达佩斯大饭店",
    "Interstellar": "星际穿越",
    "Guardians of the Galaxy": "银河护卫队",
    "The Imitation Game": "模仿游戏",
    "Deadpool": "死侍",
}


def get_chinese_title(movie_title):
    """获取电影的中文片名，找不到则返回英文原名"""
    import re
    # 去掉年份部分
    m = re.match(r'(.+?)\s*\(\d{4}\)', movie_title)
    clean_title = m.group(1).strip() if m else movie_title.strip()
    
    # 处理 "The" 在末尾的情况: "Shawshank Redemption, The" -> "The Shawshank Redemption"
    if clean_title.endswith(', The'):
        clean_title = 'The ' + clean_title[:-5]
    if clean_title.endswith(', A'):
        clean_title = 'A ' + clean_title[:-3]
    if clean_title.endswith(', An'):
        clean_title = 'An ' + clean_title[:-4]
    
    # 直接匹配
    if clean_title in CN_TITLES:
        return CN_TITLES[clean_title]
    
    # 尝试匹配部分关键字
    for en, cn in CN_TITLES.items():
        if en.lower() in clean_title.lower() or clean_title.lower() in en.lower():
            return cn
    
    # 额外处理 "The Dark Knight" 等
    if clean_title.startswith('The '):
        without_the = clean_title[4:]
        if without_the in CN_TITLES:
            return CN_TITLES[without_the]
    
    return movie_title